# Generated by Django 4.2 on 2023-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('project_image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
